; --------------------------------------------------------
; Fichier de configuration : Serveur IPBX (VoIP)
; Projet : Deploiement Telephonie HTS
; Auteur : Amine Boukherroubi
; --------------------------------------------------------

[general]
context=default
allowguest=no
udpbindaddr=0.0.0.0:5060
tcpenable=yes
tcpbindaddr=0.0.0.0:5060
disallow=all
allow=alaw       ; Codec européen standard
allow=ulaw       ; Codec américain
allow=g722       ; Codec Haute Definition (HD Voice)

; --- Ligne du Service Administration ---
[1001]
type=friend
secret=HtsSecureAdmin2026!
host=dynamic
context=administration
mailbox=1001@default
callerid="Bureau Admin" <1001>
nat=force_rport,comedia
qualify=yes      ; Permet de verifier si le telephone est en ligne

; --- Ligne de la Direction ---
[1002]
type=friend
secret=HtsSecureDir2026!
host=dynamic
context=direction
mailbox=1002@default
callerid="Direction" <1002>
qualify=yes
